-- Module 1 - Easy Task --------
-- Task 1: Show all customers who signed up after 1st March 2026.
SELECT * FROM customers
WHERE signup_date > "2026-03-01";

-- Task 2: Show all products whose price is greater than ₹2000.
SELECT * FROM products
WHERE price > 2000;

-- Task 3: Show all products sorted by price from highest to lowest.
SELECT * FROM products
ORDER BY price DESC;

-- Task 4: Display only the first 5 customers.
SELECT * FROM customers
LIMIT 5;

-- TASK 5: Show only the products in the Electronics category.
SELECT * FROM products
WHERE category = "Electronics";



-- Module 2 - Aggregate Functions -------
-- Task 1: How many customers have signed up?
SELECT COUNT(*) AS Total_customers FROM customers;   -- AS is used for giving a meaningful name to output

-- Task 2: What is the total revenue generated from all orders?
SELECT SUM(total_amount) AS Total_Revenue FROM ORDERS;   -- AS is used for giving a meaningful name to output

-- Task 3: What is the average price of all products?
SELECT AVG(price) AS Average_Price FROM products;

-- Task 4: What is the highest-priced product in your store?
SELECT MAX(price) AS highest_Price FROM products;

-- TASK 5: What is the lowest price among all products?
SELECT MIN(price) AS lowest_Price FROM products;



-- Module 3 - GROUP BY -----------
-- Task 1: How many products are there in each category?
SELECT category, COUNT(*) FROM products
GROUP BY category;

-- Task 2: What is the total revenue generated by each customer?
SELECT cust_id, SUM(total_amount) AS customer_revenue FROM orders
GROUP BY cust_id;

-- Task 3: What is the average product price in each category?
SELECT category, AVG(price) AS category_average_price FROM products
GROUP BY category;

-- Task 4: Show only the categories whose average product price is greater than ₹2000.
SELECT category, AVG(price) FROM products
GROUP BY category
HAVING AVG(price) > 2000;

-- Task 5: Show customers who have placed more than 2 orders.
SELECT cust_id, count(*) AS Total_Orders FROM orders
GROUP BY cust_id HAVING count(*) > 2;